### ISSUE TITLE
Compatibility with Image Aspect Ratio crop

### ISSUE THREAD

**Issue by maximebeguin** [mcguffin/acf-dropzone#12]
Hey, is there any chance to make this extension compatible with this custom field: https://wordpress.org/plugins/acf-image-aspect-ratio-crop/ ?

**Comment by mcguffin** [comment]
Hmm .... I have no idea why or how this could be achieved. ACF Dropzone is to make adding new files easier. 
Image Aspect Ratio Crop plugin only lets you pick existing media from the library. 
Possibly I missed something...?
