### ISSUE TITLE
Call to undefined function AcfDropzone\Compat\get_current_screen()

### ISSUE THREAD

**Issue by mvalasis** [mcguffin/acf-dropzone#14]
Hello there,

When loading a advanced form via AJAX, I sometimes get this

```
PHP Fatal error:  Uncaught Error: Call to undefined function AcfDropzone\Compat\get_current_screen() in **/wp-content/plugins/acf-dropzone/include/AcfDropzone/Compat/ACF.php:128
Stack trace:
#0 **/wp-includes/class-wp-hook.php(287): AcfDropzone\Compat\ACF->print_media_templates()
#1 **/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 **/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 **/wp-includes/media-template.php(1512): do_action()
#4 **/wp-includes/class-wp-hook.php(287): wp_print_media_templates()
#5 **/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#6 **/wp-includes/plugin.php(484): WP_Hook->do_action()
#7 **/wp-includes/general-template.php(3021): do_action() in **/wp-content/plugins/acf-dropzone/include/AcfDropzone/Compat/ACF.php on line 128
```

After googling a while, I circumvented it the same way ACF Pro does - that is by checking if the function exists first, as explained [here](https://support.advancedcustomfields.com/forums/topic/undefined-function-get_current_screen/) 

I don't know if this is the optimal solution, or if it breaks something, but it seems to work for me.
I changed line 128 of acf-dropzone/include/AcfDropzone/Compat/ACF.php
from `} else if ( $screen = get_current_screen() ) **{**`
to `} else if ( function_exists( 'get_current_screen' ) && $screen = get_current_screen() ) {`

**Comment by mcguffin** [comment]
Whoops ... thanks for letting me know!
An update is on its way.
