### ISSUE TITLE
Doesn't Work On Frontend

### ISSUE THREAD

**Issue by zachkinsey** [mcguffin/acf-dropzone#17]
It'd be nice if Users could use the dropzone on the front-end.

This plugin currently doesn't work with https://wordpress.org/plugins/acf-frontend-form-element/

**Comment by mcguffin** [comment]
I will not support acf frontend directly, but I just added some hooks that allow you to add dropping-capability to arbitrary field types. (Of course field HTML must match the HTML gernerated by ACF). More details in the README.md.

**Comment by Trarco** [comment]
What do you mean with "Of course field HTML must match the HTML gernerated by ACF"?
