### ISSUE TITLE
Dropzone fails with JavaScript error when using on site front-end

### ISSUE THREAD

**Issue by jonbrain** [mcguffin/acf-dropzone#2]
Hello,

I’m using the Dropzone plugin on the front-end of a site (using the ACF process shown here: https://www.advancedcustomfields.com/resources/create-a-front-end-form/), but it fails with a JavaScript error:

`acf-dropzone.js?ver=1.1.1:1 Uncaught TypeError: Cannot read property 'View' of undefined`

It works great in the back-end.

Any ideas?

(Apologies for the double post)

Thanks,
Jon

**Comment by jonbrain** [comment]
The problem was related to the user capabilities. User needed to be an Editor in order for the dropzone to work correctly.

Thanks,
Jon

**Comment by dangerstudios** [comment]
this problem still persists when using it in the front end, even when logged in as admin :(
