### ISSUE TITLE
How can I disable the media library?

### ISSUE THREAD

**Issue by bluestarstudios** [mcguffin/acf-dropzone#3]
Hi!

I love your implementation of a Dropzone into ACF. It works like a charm. But I'm puzzled: how can I disable the Wordpress Media Library for users? I only want to allow them to drag/drop files and/or select files from their computer. I don't want them to have access to the WP Media Library.

I would really appreciate your help with this!

Thanks!
David

**Comment by mcguffin** [comment]
Hi,
unfortunanately you can't disable the media library from the plugin. 
If you're having backbone experience, you may might find a way to remove the "Media library" tab from the "select file" modal. (But this is in wordpress core and far out of the scope of this plugin...)
