### ISSUE TITLE
Use acf-dropzone with wordplate/extended-acf

### ISSUE THREAD

**Issue by AlexVWeb** [mcguffin/acf-dropzone#5]
Hi,
I am currently using this extension with ACF Pro, but I decided to use [wordplate/extended-acf](https://github.com/wordplate/extended-acf) in order to use ACF directly in my code, and I would have liked to know if it was possible or would be possible to use ACF -Dropzone in a certain way with this one

thank you

**Comment by mcguffin** [comment]
Neat! I didn't know that one.

In theory, adding `dropzone` to the field wrapper class should do it:  
`$someField->wrapper(['class'=>'dropzone']);`

Please let me know if it worked!

**Comment by AlexVWeb** [comment]
> Neat! I didn't know that one.
> 
> In theory, adding `dropzone` to the field wrapper class should do it:
> `$someField->wrapper(['class'=>'dropzone']);`
> 
> Please let me know if it worked!

Thank-you for your prompt response.

It works perfectly, I think it might be practical for you to point this out somewhere so that we know it more simply.
