### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by NSDesign** [mcguffin/acf-dropzone#6]
Hi Jörn,

Is there meant to be an image preview once the image has uploaded via drop zone? In the same way, the image is previewed when uploaded normally.

Currently when the image has uploaded the UI returns to 'Drop files here or Add image (button)' and doesn't display the uploaded image preview. However, the image has uploaded to the Media Library.

Thanks for the plugin.

**Comment by mcguffin** [comment]
Hi, 
it should just look almost like a regular ACF File, image or Gallery field, so you might have ran int a bug.
Can you be more specific, on:
 - Your versions of WP and ACF
 - The context you are using the dropzoned file. (Post Metabox, Term, Widget, Block, optionspage, Pagebuilder, whatever, ...)
