### ISSUE TITLE
Doesn't work with "basic" uploader type

### ISSUE THREAD

**Issue by admSI** [mcguffin/acf-dropzone#9]
If you select "Basic" as the uploader type for the image field instead of "Media" then the field does not become a dropzone. The problem with this is that if you are using a front end ACF form then all image fields become "basic" if the user is not logged in. It would be great to be able to use dropzones on front end ACF forms without the user needing to be logged in.

[https://www.advancedcustomfields.com/resources/create-a-front-end-form/](https://www.advancedcustomfields.com/resources/create-a-front-end-form/)

**Comment by mcguffin** [comment]
That one should be fixed in e4525ae9930fad8fe40dcc0f0adfb09a6c88b1d9.
